---
galaxy_info:
  author: lennysh
  description: Configures a development environment (devspace) for a specific user using code-server
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - codeserver
    - vscode
    - development
    - devspace
    - ansible
    - podman

dependencies:
  - role: lennysh.devspaces.code_server

# Credits
# This role was inspired by and started with code from
# shadowman-lab/Ansible-Development by Alex Dworjan
# https://github.com/shadowman-lab/Ansible-Development
...
