---
# Discover latest version of code-server
- name: Discover latest version of code-server
  ansible.builtin.set_fact:
    version: >-
      {{
        (lookup('url', 'https://api.github.com/repos/coder/code-server/releases/latest',
                headers=_github_api_headers, split_lines=False) | from_json).get('tag_name')
        | replace('v', '')
      }}
  run_once: true
  until: version is version('0.0.0', '>=')
  retries: 10
  when: version == "latest"

# Check if code-server is already installed
- name: Check if code-server is already installed
  ansible.builtin.stat:
    path: /usr/bin/code-server
  register: code_server_installed
  changed_when: false
  failed_when: false

# Download code-server
- name: Download code-server
  ansible.builtin.get_url:
    url: "{{ codeserver_url }}"
    dest: /tmp/code-server.rpm
    mode: "0440"
  when: not code_server_installed.stat.exists

# Install Code Server
- name: Install Code Server
  ansible.builtin.dnf:
    name: /tmp/code-server.rpm
    state: present
    disable_gpg_check: true
  when: not code_server_installed.stat.exists

- name: Verify code-server installation
  ansible.builtin.stat:
    path: /usr/bin/code-server
  register: code_server_path
  changed_when: false
  failed_when: not code_server_path.stat.exists

- name: Display code-server installation info
  ansible.builtin.debug:
    msg: "code-server is installed at /usr/bin/code-server"

# Install system-wide dependencies required for devspaces
- name: Install podman and git and python 3.11
  ansible.builtin.dnf:
    name:
      - podman
      - git
      - python3.11
      - python3.11-pip
      - python3-firewall
    state: present
...
