FROM quay.io/devfile/base-developer-image:ubi9-latest

ARG PYV=3.11

LABEL org.opencontainers.image.source=https://github.com/lennysh/podman_devspaces/tree/devel/containers/ansible-dev-space
LABEL org.opencontainers.image.authors="Lenny Shirley <lshirley@redhat.com>"
LABEL org.opencontainers.image.licenses="GPL-3.0"
LABEL org.opencontainers.image.description="A Podman Dev Spaces container image for Ansible."

# Set an environment variable for the code-server version.
# You can check for the latest version here: https://github.com/coder/code-server/releases
ENV CODE_SERVER_VERSION="{{ podman_build_code_server_version }}"

USER 0

WORKDIR /context
# install ansible-dev-tools specific packages and dependencies while avoiding
# adding multiple layers to the image.
RUN --mount=type=bind,target=. --mount=type=cache,dst=/var/cache/dnf --mount=type=cache,dst=/root/.cache/pip ./setup.sh

# Download and install VSCode Server (code-server)
# We move the entire directory and symlink the executable to ensure
# it can find all its dependencies (like the node binary).
RUN sudo curl -fL "https://github.com/coder/code-server/releases/download/v${CODE_SERVER_VERSION}/code-server-${CODE_SERVER_VERSION}-linux-amd64.tar.gz" \
    -o code-server.tar.gz && \
    tar -xzf code-server.tar.gz && \
    mv "code-server-${CODE_SERVER_VERSION}-linux-amd64" /usr/lib/code-server && \
    ln -s /usr/lib/code-server/bin/code-server /usr/local/bin/code-server && \
    # Clean up downloaded files
    rm code-server.tar.gz

# Copy the entrypoint script and make it executable
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Expose the default port for code-server.
EXPOSE 8080

# Set the entrypoint to our new script.
ENTRYPOINT ["entrypoint.sh"]

